version: '3.8'

services:
  app:
    build: .
    container_name: wallet_app
    ports:
      - "8081:8081"
    environment:
      # Use host.docker.internal to connect to the local postgresql database on Ubuntu
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/springboot_db
    extra_hosts:
      - "host.docker.internal:host-gateway"
